repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      # - id: check-json
      # - id: check-added-large-files
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.1.0
  #   hooks:
  #     - id: prettier
  #       types_or: [javascript, jsx, ts, tsx, json, css, scss, yaml]
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.56.0
  #   hooks:
  #     - id: eslint
  #       files: \.[jt]sx?$
  #       types: [file]
  #       additional_dependencies:
  #         - eslint
  #         - eslint-config-prettier
  - repo: local
    hooks:
      - id: generate-env
        name: Generate Environment File
        entry: node generate-env.js
        language: node
        files: ^(\.env\.development|generate-env\.js)$
        pass_filenames: false
        always_run: true
