name: Push to staging wlxvue.bizbybot.com 

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - devwork
  
jobs:
  deploy:
    name: Deploy to DO on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
      
        uses: actions/checkout@v1

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR_M }}
