name: Push to staging wlxvue.bizbybot.com 

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - devwork
  
jobs:
  deploy:
    name: Push to staging from devwork branch
    runs-on: ubuntu-latest
steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Create Node Environment
              uses: actions/setup-node@v1
              with: 
                node-version: 10.x
            - name: Install Packages and Build Application
              run: |
                npm install -g @vue/cli yarn
                yarn install
                yarn build
            - name: Deploy
              uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR_M }}
