name: Push-to-development-testing

on:
  push:
    branches:
      - devwork

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm install
    - run: npx vite build
    - run: npm run build

    - name: ssh deploy on aws ec2
      uses: easingthemes/ssh-deploy@v2.1.4
      with:
        source: "dist/"
        target: ${{ secrets.TARGET_DIR_M }}
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
