name: Push to staging wlxvue.bizbybot.com 

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - devwork
  
jobs:
  deploy:
    name: Push to staging from devwork branch
    runs-on: ubuntu-latest
steps:
      uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: Installing project dependencies
      run: npm install
      - name: Building the project
      run: npm run build
    uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR_M }}
